name: Request a new carrier
description: Request a new carrier to be added to the list of supported carriers.
assignees:
  - art29
body:
  - type: input
    attributes:
      label: Carrier name
      description: The name of the carrier you would like to see added.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information you would like to provide.
    validations:
      required: false